openapi: 3.0.0
info:
  title: Sample Product API
  version: v1.3.1 # バージョンを更新 (Attributeスキーマの 'attribute' -> 'code' キー名変更)
  description: API for managing products and attributes. Params are managed via dedicated endpoints. Attribute creation/update does not include params list directly. Schema key names updated to snake_case. Attribute key 'attribute' renamed to 'code'.
servers:
  - url: http://localhost:8080/api # Example server URL
    description: Development server

tags:
  - name: Products
    description: Product related operations
  - name: Attributes
    description: Attribute related operations
  - name: Parameters
    description: Parameter related operations
  - name: Utilities
    description: Utility operations for the mock server

components:
  schemas:
    # --- Base Schemas (primarily for responses or when ID is known) ---
    ParamBase:
      type: object
      properties:
        param_id:
          type: integer
          description: Unique identifier for the parameter.
          readOnly: true
        sort_order:
          type: integer
      required:
        - param_id
        - sort_order

    ParamType1Item:
      allOf:
        - $ref: "#/components/schemas/ParamBase"
        - type: object
          properties:
            type:
              type: string
              enum: [type1]
            code:
              type: string
            disp_name:
              type: string
          required:
            - type
            - code
            - disp_name

    ParamType2Item:
      allOf:
        - $ref: "#/components/schemas/ParamBase"
        - type: object
          properties:
            type:
              type: string
              enum: [type2]
            min:
              type: integer
            increment:
              type: integer
          required:
            - type
            - min
            - increment

    ParamType3Item:
      allOf:
        - $ref: "#/components/schemas/ParamBase"
        - type: object
          properties:
            type:
              type: string
              enum: [type3]
            code:
              type: string
            disp_name:
              type: string
          required:
            - type
            - code
            - disp_name

    ParamItem: # For GET responses primarily
      oneOf:
        - $ref: "#/components/schemas/ParamType1Item"
        - $ref: "#/components/schemas/ParamType2Item"
        - $ref: "#/components/schemas/ParamType3Item"
      discriminator:
        propertyName: type
        mapping:
          type1: "#/components/schemas/ParamType1Item"
          type2: "#/components/schemas/ParamType2Item"
          type3: "#/components/schemas/ParamType3Item"

    Attribute: # For GET responses primarily
      type: object
      properties:
        attribute_id:
          type: integer
          readOnly: true
        code: # MODIFIED from 'attribute' to 'code'
          type: string
          description: Code identifier for the attribute (formerly 'attribute').
        data_type:
          type: string
        disp_name:
          type: string
        unit:
          type: string
        params:
          type: array
          items:
            $ref: "#/components/schemas/ParamItem"
          description: List of parameters. Managed via /params endpoint. Included in GET, empty on new attribute creation.
        contract:
          type: string
        public:
          type: boolean
        masking:
          type: boolean
        online:
          type: boolean
        sort_order:
          type: integer
      required:
        - attribute_id
        - code # MODIFIED from 'attribute'
        - data_type
        - disp_name
        - unit
        - params
        - contract
        - public
        - masking
        - online
        - sort_order

    Product: # For GET responses primarily
      type: object
      properties:
        prod_id:
          type: integer
          readOnly: true
        prefix:
          type: string
        prd_type:
          type: string
        cfg_type:
          type: string
        attributes:
          type: array
          items:
            $ref: "#/components/schemas/Attribute"
        sort_order:
          type: integer
      required:
        - prod_id
        - prefix
        - prd_type
        - cfg_type
        - attributes
        - sort_order

    # --- Input Schemas (for POST/PUT request bodies) ---
    ParamBaseInput:
      type: object
      properties:
        sort_order:
          type: integer
      required:
        - sort_order

    ParamType1ItemInput:
      allOf:
        - $ref: "#/components/schemas/ParamBaseInput"
        - type: object
          properties:
            type:
              type: string
              enum: [type1]
            code:
              type: string
            disp_name:
              type: string
          required:
            - type
            - code
            - disp_name

    ParamType2ItemInput:
      allOf:
        - $ref: "#/components/schemas/ParamBaseInput"
        - type: object
          properties:
            type:
              type: string
              enum: [type2]
            min:
              type: integer
            increment:
              type: integer
          required:
            - type
            - min
            - increment

    ParamType3ItemInput:
      allOf:
        - $ref: "#/components/schemas/ParamBaseInput"
        - type: object
          properties:
            type:
              type: string
              enum: [type3]
            code:
              type: string
            disp_name:
              type: string
          required:
            - type
            - code
            - disp_name

    ParamItemInput: # For POST/PUT request bodies for Parameters
      oneOf:
        - $ref: "#/components/schemas/ParamType1ItemInput"
        - $ref: "#/components/schemas/ParamType2ItemInput"
        - $ref: "#/components/schemas/ParamType3ItemInput"
      discriminator:
        propertyName: type
        mapping:
          type1: "#/components/schemas/ParamType1ItemInput"
          type2: "#/components/schemas/ParamType2ItemInput"
          type3: "#/components/schemas/ParamType3ItemInput"

    AttributeInput: # For POST/PUT request bodies for Attributes
      type: object
      properties:
        # attribute_id is excluded
        code: # MODIFIED from 'attribute' to 'code'
          type: string
          description: Code identifier for the attribute (formerly 'attribute').
        data_type:
          type: string
        disp_name:
          type: string
        unit:
          type: string
        # params field is EXCLUDED
        contract:
          type: string
        public:
          type: boolean
        masking:
          type: boolean
        online:
          type: boolean
        sort_order:
          type: integer
      required:
        - code # MODIFIED from 'attribute'
        - data_type
        - disp_name
        - unit
        # params is EXCLUDED
        - contract
        - public
        - masking
        - online
        - sort_order

    # --- Error Schema ---
    Error:
      type: object
      properties:
        message:
          type: string
        code: # Error code (string, optional)
          type: string
      required:
        - message

  parameters: # Path parameters - names remain camelCase as they are part of the URL structure
    ProductIdParameter:
      name: productId
      in: path
      required: true
      schema:
        type: integer
    AttributeIdParameter:
      name: attributeId
      in: path
      required: true
      schema:
        type: integer
    ParamIdParameter:
      name: paramId
      in: path
      required: true
      schema:
        type: integer

  responses:
    NotFound:
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    BadRequest:
      description: The request was malformed or invalid.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    InternalServerError:
      description: An unexpected error occurred on the server.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

paths:
  /products:
    get:
      summary: List all products
      operationId: listProducts
      tags:
        - Products
      responses:
        "200":
          description: A list of all products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /products/{productId}:
    get:
      summary: Get a specific product by its ID
      operationId: getProductById
      tags:
        - Products
      parameters:
        - $ref: "#/components/parameters/ProductIdParameter"
      responses:
        "200":
          description: The requested product.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /products/{productId}/attributes:
    post:
      summary: Add a new attribute to a specific product (without params)
      operationId: addAttribute
      tags:
        - Attributes
      parameters:
        - $ref: "#/components/parameters/ProductIdParameter"
      requestBody:
        description: The attribute to add. `attribute_id` and `params` list are server-managed and should not be provided.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttributeInput"
      responses:
        "201":
          description: Attribute created successfully. Returns the created attribute (params will be an empty array initially).
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Attribute"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          description: Product not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /products/{productId}/attributes/{attributeId}:
    put:
      summary: Update an existing attribute of a specific product (without managing params list directly)
      operationId: updateAttribute
      tags:
        - Attributes
      parameters:
        - $ref: "#/components/parameters/ProductIdParameter"
        - $ref: "#/components/parameters/AttributeIdParameter"
      requestBody:
        description: The updated attribute data. `attribute_id` is from the path. `params` list is not modified by this endpoint.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttributeInput"
      responses:
        "200":
          description: Attribute updated successfully. Returns the updated attribute (params list reflects current state, not directly changed by this PUT).
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Attribute"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          description: Product or Attribute not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          $ref: "#/components/responses/InternalServerError"
    delete:
      summary: Delete a specific attribute from a product
      operationId: deleteAttribute
      tags:
        - Attributes
      parameters:
        - $ref: "#/components/parameters/ProductIdParameter"
        - $ref: "#/components/parameters/AttributeIdParameter"
      responses:
        "204":
          description: Attribute deleted successfully.
        "404":
          description: Product or Attribute not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /products/{productId}/attributes/{attributeId}/params:
    post:
      summary: Add a new parameter to a specific attribute
      operationId: addParam
      tags:
        - Parameters
      parameters:
        - $ref: "#/components/parameters/ProductIdParameter"
        - $ref: "#/components/parameters/AttributeIdParameter"
      requestBody:
        description: The parameter to add. `param_id` will be assigned by the server.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParamItemInput"
      responses:
        "201":
          description: Parameter created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ParamItem"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          description: Product or Attribute not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /products/{productId}/attributes/{attributeId}/params/{paramId}:
    put:
      summary: Update an existing parameter of a specific attribute
      operationId: updateParam
      tags:
        - Parameters
      parameters:
        - $ref: "#/components/parameters/ProductIdParameter"
        - $ref: "#/components/parameters/AttributeIdParameter"
        - $ref: "#/components/parameters/ParamIdParameter"
      requestBody:
        description: The updated parameter data. `param_id` is from the path.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParamItemInput"
      responses:
        "200":
          description: Parameter updated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ParamItem"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          description: Product, Attribute, or Parameter not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          $ref: "#/components/responses/InternalServerError"
    delete:
      summary: Delete a specific parameter from an attribute
      operationId: deleteParam
      tags:
        - Parameters
      parameters:
        - $ref: "#/components/parameters/ProductIdParameter"
        - $ref: "#/components/parameters/AttributeIdParameter"
        - $ref: "#/components/parameters/ParamIdParameter"
      responses:
        "204":
          description: Parameter deleted successfully.
        "404":
          description: Product, Attribute, or Parameter not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /refresh:
    post:
      summary: Reset all mock data to its initial state
      operationId: refreshMockData
      tags:
        - Utilities
      responses:
        "200":
          description: Mock data has been successfully reset.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Mock data has been reset to the initial state.
        "500":
          description: Internal server error occurred during data reset.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
