/* tslint:disable */
/* eslint-disable */
/**
 * Sample Product API
 * API for managing products and attributes. Params are managed via dedicated endpoints. Attribute creation/update does not include params list directly. \'param\' field in Attribute renamed to \'params\'. Corrected tags for DELETE methods.
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttributeInput
 */
export interface AttributeInput {
    /**
     * 
     * @type {string}
     * @memberof AttributeInput
     */
    attribute: string;
    /**
     * 
     * @type {string}
     * @memberof AttributeInput
     */
    attributeType: string;
    /**
     * 
     * @type {string}
     * @memberof AttributeInput
     */
    attributeJP: string;
    /**
     * 
     * @type {string}
     * @memberof AttributeInput
     */
    attributeUnit: string;
    /**
     * 
     * @type {string}
     * @memberof AttributeInput
     */
    contract: string;
    /**
     * 
     * @type {boolean}
     * @memberof AttributeInput
     */
    _public: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AttributeInput
     */
    masking: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AttributeInput
     */
    online: boolean;
    /**
     * 
     * @type {number}
     * @memberof AttributeInput
     */
    sortOrder: number;
}

/**
 * Check if a given object implements the AttributeInput interface.
 */
export function instanceOfAttributeInput(value: object): value is AttributeInput {
    if (!('attribute' in value) || value['attribute'] === undefined) return false;
    if (!('attributeType' in value) || value['attributeType'] === undefined) return false;
    if (!('attributeJP' in value) || value['attributeJP'] === undefined) return false;
    if (!('attributeUnit' in value) || value['attributeUnit'] === undefined) return false;
    if (!('contract' in value) || value['contract'] === undefined) return false;
    if (!('_public' in value) || value['_public'] === undefined) return false;
    if (!('masking' in value) || value['masking'] === undefined) return false;
    if (!('online' in value) || value['online'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    return true;
}

export function AttributeInputFromJSON(json: any): AttributeInput {
    return AttributeInputFromJSONTyped(json, false);
}

export function AttributeInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeInput {
    if (json == null) {
        return json;
    }
    return {
        
        'attribute': json['attribute'],
        'attributeType': json['attributeType'],
        'attributeJP': json['attributeJP'],
        'attributeUnit': json['attributeUnit'],
        'contract': json['contract'],
        '_public': json['public'],
        'masking': json['masking'],
        'online': json['online'],
        'sortOrder': json['sortOrder'],
    };
}

export function AttributeInputToJSON(json: any): AttributeInput {
    return AttributeInputToJSONTyped(json, false);
}

export function AttributeInputToJSONTyped(value?: AttributeInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attribute': value['attribute'],
        'attributeType': value['attributeType'],
        'attributeJP': value['attributeJP'],
        'attributeUnit': value['attributeUnit'],
        'contract': value['contract'],
        'public': value['_public'],
        'masking': value['masking'],
        'online': value['online'],
        'sortOrder': value['sortOrder'],
    };
}

