/* tslint:disable */
/* eslint-disable */
/**
 * Sample Product API
 * API for managing products and attributes. Params are managed via dedicated endpoints. Attribute creation/update does not include params list directly. \'param\' field in Attribute renamed to \'params\'. Corrected tags for DELETE methods.
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParamBaseInput
 */
export interface ParamBaseInput {
    /**
     * 
     * @type {number}
     * @memberof ParamBaseInput
     */
    sortOrder: number;
}

/**
 * Check if a given object implements the ParamBaseInput interface.
 */
export function instanceOfParamBaseInput(value: object): value is ParamBaseInput {
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    return true;
}

export function ParamBaseInputFromJSON(json: any): ParamBaseInput {
    return ParamBaseInputFromJSONTyped(json, false);
}

export function ParamBaseInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParamBaseInput {
    if (json == null) {
        return json;
    }
    return {
        
        'sortOrder': json['sortOrder'],
    };
}

export function ParamBaseInputToJSON(json: any): ParamBaseInput {
    return ParamBaseInputToJSONTyped(json, false);
}

export function ParamBaseInputToJSONTyped(value?: ParamBaseInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sortOrder': value['sortOrder'],
    };
}

