/* tslint:disable */
/* eslint-disable */
/**
 * Sample Product API
 * API for managing products and attributes. Params are managed via dedicated endpoints. Attribute creation/update does not include params list directly. \'param\' field in Attribute renamed to \'params\'. Corrected tags for DELETE methods.
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParamType3Item
 */
export interface ParamType3Item {
    /**
     * Unique identifier for the parameter.
     * @type {number}
     * @memberof ParamType3Item
     */
    readonly paramId: number;
    /**
     * 
     * @type {number}
     * @memberof ParamType3Item
     */
    sortOrder: number;
    /**
     * 
     * @type {string}
     * @memberof ParamType3Item
     */
    type: ParamType3ItemTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ParamType3Item
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ParamType3Item
     */
    dispName: string;
}


/**
 * @export
 */
export const ParamType3ItemTypeEnum = {
    Type3: 'type3'
} as const;
export type ParamType3ItemTypeEnum = typeof ParamType3ItemTypeEnum[keyof typeof ParamType3ItemTypeEnum];


/**
 * Check if a given object implements the ParamType3Item interface.
 */
export function instanceOfParamType3Item(value: object): value is ParamType3Item {
    if (!('paramId' in value) || value['paramId'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('dispName' in value) || value['dispName'] === undefined) return false;
    return true;
}

export function ParamType3ItemFromJSON(json: any): ParamType3Item {
    return ParamType3ItemFromJSONTyped(json, false);
}

export function ParamType3ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParamType3Item {
    if (json == null) {
        return json;
    }
    return {
        
        'paramId': json['paramId'],
        'sortOrder': json['sortOrder'],
        'type': json['type'],
        'code': json['code'],
        'dispName': json['dispName'],
    };
}

export function ParamType3ItemToJSON(json: any): ParamType3Item {
    return ParamType3ItemToJSONTyped(json, false);
}

export function ParamType3ItemToJSONTyped(value?: Omit<ParamType3Item, 'paramId'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sortOrder': value['sortOrder'],
        'type': value['type'],
        'code': value['code'],
        'dispName': value['dispName'],
    };
}

