/* tslint:disable */
/* eslint-disable */
/**
 * Sample Product API
 * API for managing products and attributes. Params are managed via dedicated endpoints. Attribute creation/update does not include params list directly. \'param\' field in Attribute renamed to \'params\'. Corrected tags for DELETE methods.
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * @type ParamItemInput
 * 
 * @export
 */
export type ParamItemInput = { type: 'type1' } & ParamType1ItemInput | { type: 'type2' } & ParamType2ItemInput | { type: 'type3' } & ParamType3ItemInput;

export function ParamItemInputFromJSON(json: any): ParamItemInput {
    return ParamItemInputFromJSONTyped(json, false);
}

export function ParamItemInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParamItemInput {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'type1':
            return Object.assign({}, ParamType1ItemInputFromJSONTyped(json, true), { type: 'type1' } as const);
        case 'type2':
            return Object.assign({}, ParamType2ItemInputFromJSONTyped(json, true), { type: 'type2' } as const);
        case 'type3':
            return Object.assign({}, ParamType3ItemInputFromJSONTyped(json, true), { type: 'type3' } as const);
        default:
            return json;
    }
}

export function ParamItemInputToJSON(json: any): any {
    return ParamItemInputToJSONTyped(json, false);
}

export function ParamItemInputToJSONTyped(value?: ParamItemInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'type1':
            return Object.assign({}, ParamType1ItemInputToJSON(value), { type: 'type1' } as const);
        case 'type2':
            return Object.assign({}, ParamType2ItemInputToJSON(value), { type: 'type2' } as const);
        case 'type3':
            return Object.assign({}, ParamType3ItemInputToJSON(value), { type: 'type3' } as const);
        default:
            return json;
    }
}

