/* tslint:disable */
/* eslint-disable */
/**
 * Sample Product API
 * API for managing products and attributes. Params are managed via dedicated endpoints. Attribute creation/update does not include params list directly. \'param\' field in Attribute renamed to \'params\'. Corrected tags for DELETE methods.
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParamType2ItemInput
 */
export interface ParamType2ItemInput {
    /**
     * 
     * @type {number}
     * @memberof ParamType2ItemInput
     */
    sortOrder: number;
    /**
     * 
     * @type {string}
     * @memberof ParamType2ItemInput
     */
    type: ParamType2ItemInputTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ParamType2ItemInput
     */
    min: number;
    /**
     * 
     * @type {number}
     * @memberof ParamType2ItemInput
     */
    increment: number;
}


/**
 * @export
 */
export const ParamType2ItemInputTypeEnum = {
    Type2: 'type2'
} as const;
export type ParamType2ItemInputTypeEnum = typeof ParamType2ItemInputTypeEnum[keyof typeof ParamType2ItemInputTypeEnum];


/**
 * Check if a given object implements the ParamType2ItemInput interface.
 */
export function instanceOfParamType2ItemInput(value: object): value is ParamType2ItemInput {
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('min' in value) || value['min'] === undefined) return false;
    if (!('increment' in value) || value['increment'] === undefined) return false;
    return true;
}

export function ParamType2ItemInputFromJSON(json: any): ParamType2ItemInput {
    return ParamType2ItemInputFromJSONTyped(json, false);
}

export function ParamType2ItemInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParamType2ItemInput {
    if (json == null) {
        return json;
    }
    return {
        
        'sortOrder': json['sortOrder'],
        'type': json['type'],
        'min': json['min'],
        'increment': json['increment'],
    };
}

export function ParamType2ItemInputToJSON(json: any): ParamType2ItemInput {
    return ParamType2ItemInputToJSONTyped(json, false);
}

export function ParamType2ItemInputToJSONTyped(value?: ParamType2ItemInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sortOrder': value['sortOrder'],
        'type': value['type'],
        'min': value['min'],
        'increment': value['increment'],
    };
}

