/* tslint:disable */
/* eslint-disable */
/**
 * Sample Product API
 * API for managing products and attributes. Params are managed via dedicated endpoints. Attribute creation/update does not include params list directly. \'param\' field in Attribute renamed to \'params\'. Corrected tags for DELETE methods.
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParamType3ItemInput
 */
export interface ParamType3ItemInput {
    /**
     * 
     * @type {number}
     * @memberof ParamType3ItemInput
     */
    sortOrder: number;
    /**
     * 
     * @type {string}
     * @memberof ParamType3ItemInput
     */
    type: ParamType3ItemInputTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ParamType3ItemInput
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ParamType3ItemInput
     */
    dispName: string;
}


/**
 * @export
 */
export const ParamType3ItemInputTypeEnum = {
    Type3: 'type3'
} as const;
export type ParamType3ItemInputTypeEnum = typeof ParamType3ItemInputTypeEnum[keyof typeof ParamType3ItemInputTypeEnum];


/**
 * Check if a given object implements the ParamType3ItemInput interface.
 */
export function instanceOfParamType3ItemInput(value: object): value is ParamType3ItemInput {
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('dispName' in value) || value['dispName'] === undefined) return false;
    return true;
}

export function ParamType3ItemInputFromJSON(json: any): ParamType3ItemInput {
    return ParamType3ItemInputFromJSONTyped(json, false);
}

export function ParamType3ItemInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParamType3ItemInput {
    if (json == null) {
        return json;
    }
    return {
        
        'sortOrder': json['sortOrder'],
        'type': json['type'],
        'code': json['code'],
        'dispName': json['dispName'],
    };
}

export function ParamType3ItemInputToJSON(json: any): ParamType3ItemInput {
    return ParamType3ItemInputToJSONTyped(json, false);
}

export function ParamType3ItemInputToJSONTyped(value?: ParamType3ItemInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sortOrder': value['sortOrder'],
        'type': value['type'],
        'code': value['code'],
        'dispName': value['dispName'],
    };
}

