/* tslint:disable */
/* eslint-disable */
/**
 * Sample Product API
 * API for managing products and attributes. Params are managed via dedicated endpoints. Attribute creation/update does not include params list directly. \'param\' field in Attribute renamed to \'params\'. Corrected tags for DELETE methods.
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParamBase
 */
export interface ParamBase {
    /**
     * Unique identifier for the parameter.
     * @type {number}
     * @memberof ParamBase
     */
    readonly paramId: number;
    /**
     * 
     * @type {number}
     * @memberof ParamBase
     */
    sortOrder: number;
}

/**
 * Check if a given object implements the ParamBase interface.
 */
export function instanceOfParamBase(value: object): value is ParamBase {
    if (!('paramId' in value) || value['paramId'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    return true;
}

export function ParamBaseFromJSON(json: any): ParamBase {
    return ParamBaseFromJSONTyped(json, false);
}

export function ParamBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParamBase {
    if (json == null) {
        return json;
    }
    return {
        
        'paramId': json['paramId'],
        'sortOrder': json['sortOrder'],
    };
}

export function ParamBaseToJSON(json: any): ParamBase {
    return ParamBaseToJSONTyped(json, false);
}

export function ParamBaseToJSONTyped(value?: Omit<ParamBase, 'paramId'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sortOrder': value['sortOrder'],
    };
}

