/* tslint:disable */
/* eslint-disable */
/**
 * Sample Product API
 * API for managing products and attributes. Params are managed via dedicated endpoints. Attribute creation/update does not include params list directly. \'param\' field in Attribute renamed to \'params\'. Corrected tags for DELETE methods.
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshMockData200Response
 */
export interface RefreshMockData200Response {
    /**
     * 
     * @type {string}
     * @memberof RefreshMockData200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the RefreshMockData200Response interface.
 */
export function instanceOfRefreshMockData200Response(value: object): value is RefreshMockData200Response {
    return true;
}

export function RefreshMockData200ResponseFromJSON(json: any): RefreshMockData200Response {
    return RefreshMockData200ResponseFromJSONTyped(json, false);
}

export function RefreshMockData200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshMockData200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function RefreshMockData200ResponseToJSON(json: any): RefreshMockData200Response {
    return RefreshMockData200ResponseToJSONTyped(json, false);
}

export function RefreshMockData200ResponseToJSONTyped(value?: RefreshMockData200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

