from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ParamType2ItemInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sort_order=None, type=None, min=None, increment=None):  # noqa: E501
        """ParamType2ItemInput - a model defined in OpenAPI

        :param sort_order: The sort_order of this ParamType2ItemInput.  # noqa: E501
        :type sort_order: int
        :param type: The type of this ParamType2ItemInput.  # noqa: E501
        :type type: str
        :param min: The min of this ParamType2ItemInput.  # noqa: E501
        :type min: int
        :param increment: The increment of this ParamType2ItemInput.  # noqa: E501
        :type increment: int
        """
        self.openapi_types = {
            'sort_order': int,
            'type': str,
            'min': int,
            'increment': int
        }

        self.attribute_map = {
            'sort_order': 'sort_order',
            'type': 'type',
            'min': 'min',
            'increment': 'increment'
        }

        self._sort_order = sort_order
        self._type = type
        self._min = min
        self._increment = increment

    @classmethod
    def from_dict(cls, dikt) -> 'ParamType2ItemInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParamType2ItemInput of this ParamType2ItemInput.  # noqa: E501
        :rtype: ParamType2ItemInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sort_order(self) -> int:
        """Gets the sort_order of this ParamType2ItemInput.


        :return: The sort_order of this ParamType2ItemInput.
        :rtype: int
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order: int):
        """Sets the sort_order of this ParamType2ItemInput.


        :param sort_order: The sort_order of this ParamType2ItemInput.
        :type sort_order: int
        """
        if sort_order is None:
            raise ValueError("Invalid value for `sort_order`, must not be `None`")  # noqa: E501

        self._sort_order = sort_order

    @property
    def type(self) -> str:
        """Gets the type of this ParamType2ItemInput.


        :return: The type of this ParamType2ItemInput.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ParamType2ItemInput.


        :param type: The type of this ParamType2ItemInput.
        :type type: str
        """
        allowed_values = ["type2"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def min(self) -> int:
        """Gets the min of this ParamType2ItemInput.


        :return: The min of this ParamType2ItemInput.
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min: int):
        """Sets the min of this ParamType2ItemInput.


        :param min: The min of this ParamType2ItemInput.
        :type min: int
        """
        if min is None:
            raise ValueError("Invalid value for `min`, must not be `None`")  # noqa: E501

        self._min = min

    @property
    def increment(self) -> int:
        """Gets the increment of this ParamType2ItemInput.


        :return: The increment of this ParamType2ItemInput.
        :rtype: int
        """
        return self._increment

    @increment.setter
    def increment(self, increment: int):
        """Sets the increment of this ParamType2ItemInput.


        :param increment: The increment of this ParamType2ItemInput.
        :type increment: int
        """
        if increment is None:
            raise ValueError("Invalid value for `increment`, must not be `None`")  # noqa: E501

        self._increment = increment
