from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ParamType1Item(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, param_id=None, sort_order=None, type=None, code=None, disp_name=None):  # noqa: E501
        """ParamType1Item - a model defined in OpenAPI

        :param param_id: The param_id of this ParamType1Item.  # noqa: E501
        :type param_id: int
        :param sort_order: The sort_order of this ParamType1Item.  # noqa: E501
        :type sort_order: int
        :param type: The type of this ParamType1Item.  # noqa: E501
        :type type: str
        :param code: The code of this ParamType1Item.  # noqa: E501
        :type code: str
        :param disp_name: The disp_name of this ParamType1Item.  # noqa: E501
        :type disp_name: str
        """
        self.openapi_types = {
            'param_id': int,
            'sort_order': int,
            'type': str,
            'code': str,
            'disp_name': str
        }

        self.attribute_map = {
            'param_id': 'param_id',
            'sort_order': 'sort_order',
            'type': 'type',
            'code': 'code',
            'disp_name': 'disp_name'
        }

        self._param_id = param_id
        self._sort_order = sort_order
        self._type = type
        self._code = code
        self._disp_name = disp_name

    @classmethod
    def from_dict(cls, dikt) -> 'ParamType1Item':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParamType1Item of this ParamType1Item.  # noqa: E501
        :rtype: ParamType1Item
        """
        return util.deserialize_model(dikt, cls)

    @property
    def param_id(self) -> int:
        """Gets the param_id of this ParamType1Item.

        Unique identifier for the parameter.  # noqa: E501

        :return: The param_id of this ParamType1Item.
        :rtype: int
        """
        return self._param_id

    @param_id.setter
    def param_id(self, param_id: int):
        """Sets the param_id of this ParamType1Item.

        Unique identifier for the parameter.  # noqa: E501

        :param param_id: The param_id of this ParamType1Item.
        :type param_id: int
        """
        if param_id is None:
            raise ValueError("Invalid value for `param_id`, must not be `None`")  # noqa: E501

        self._param_id = param_id

    @property
    def sort_order(self) -> int:
        """Gets the sort_order of this ParamType1Item.


        :return: The sort_order of this ParamType1Item.
        :rtype: int
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order: int):
        """Sets the sort_order of this ParamType1Item.


        :param sort_order: The sort_order of this ParamType1Item.
        :type sort_order: int
        """
        if sort_order is None:
            raise ValueError("Invalid value for `sort_order`, must not be `None`")  # noqa: E501

        self._sort_order = sort_order

    @property
    def type(self) -> str:
        """Gets the type of this ParamType1Item.


        :return: The type of this ParamType1Item.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ParamType1Item.


        :param type: The type of this ParamType1Item.
        :type type: str
        """
        allowed_values = ["type1"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def code(self) -> str:
        """Gets the code of this ParamType1Item.


        :return: The code of this ParamType1Item.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this ParamType1Item.


        :param code: The code of this ParamType1Item.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def disp_name(self) -> str:
        """Gets the disp_name of this ParamType1Item.


        :return: The disp_name of this ParamType1Item.
        :rtype: str
        """
        return self._disp_name

    @disp_name.setter
    def disp_name(self, disp_name: str):
        """Sets the disp_name of this ParamType1Item.


        :param disp_name: The disp_name of this ParamType1Item.
        :type disp_name: str
        """
        if disp_name is None:
            raise ValueError("Invalid value for `disp_name`, must not be `None`")  # noqa: E501

        self._disp_name = disp_name
