from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.param_type1_item_input import ParamType1ItemInput
from openapi_server.models.param_type2_item_input import ParamType2ItemInput
from openapi_server.models.param_type3_item_input import ParamType3ItemInput
from openapi_server import util

from openapi_server.models.param_type1_item_input import ParamType1ItemInput  # noqa: E501
from openapi_server.models.param_type2_item_input import ParamType2ItemInput  # noqa: E501
from openapi_server.models.param_type3_item_input import ParamType3ItemInput  # noqa: E501

class ParamItemInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sort_order=None, type=None, code=None, disp_name=None, min=None, increment=None):  # noqa: E501
        """ParamItemInput - a model defined in OpenAPI

        :param sort_order: The sort_order of this ParamItemInput.  # noqa: E501
        :type sort_order: int
        :param type: The type of this ParamItemInput.  # noqa: E501
        :type type: str
        :param code: The code of this ParamItemInput.  # noqa: E501
        :type code: str
        :param disp_name: The disp_name of this ParamItemInput.  # noqa: E501
        :type disp_name: str
        :param min: The min of this ParamItemInput.  # noqa: E501
        :type min: int
        :param increment: The increment of this ParamItemInput.  # noqa: E501
        :type increment: int
        """
        self.openapi_types = {
            'sort_order': int,
            'type': str,
            'code': str,
            'disp_name': str,
            'min': int,
            'increment': int
        }

        self.attribute_map = {
            'sort_order': 'sortOrder',
            'type': 'type',
            'code': 'code',
            'disp_name': 'dispName',
            'min': 'min',
            'increment': 'increment'
        }

        self._sort_order = sort_order
        self._type = type
        self._code = code
        self._disp_name = disp_name
        self._min = min
        self._increment = increment

    @classmethod
    def from_dict(cls, dikt) -> 'ParamItemInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParamItemInput of this ParamItemInput.  # noqa: E501
        :rtype: ParamItemInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sort_order(self) -> int:
        """Gets the sort_order of this ParamItemInput.


        :return: The sort_order of this ParamItemInput.
        :rtype: int
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order: int):
        """Sets the sort_order of this ParamItemInput.


        :param sort_order: The sort_order of this ParamItemInput.
        :type sort_order: int
        """
        if sort_order is None:
            raise ValueError("Invalid value for `sort_order`, must not be `None`")  # noqa: E501

        self._sort_order = sort_order

    @property
    def type(self) -> str:
        """Gets the type of this ParamItemInput.


        :return: The type of this ParamItemInput.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ParamItemInput.


        :param type: The type of this ParamItemInput.
        :type type: str
        """
        allowed_values = ["type1", "type2", "type3"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def code(self) -> str:
        """Gets the code of this ParamItemInput.


        :return: The code of this ParamItemInput.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this ParamItemInput.


        :param code: The code of this ParamItemInput.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def disp_name(self) -> str:
        """Gets the disp_name of this ParamItemInput.


        :return: The disp_name of this ParamItemInput.
        :rtype: str
        """
        return self._disp_name

    @disp_name.setter
    def disp_name(self, disp_name: str):
        """Sets the disp_name of this ParamItemInput.


        :param disp_name: The disp_name of this ParamItemInput.
        :type disp_name: str
        """
        if disp_name is None:
            raise ValueError("Invalid value for `disp_name`, must not be `None`")  # noqa: E501

        self._disp_name = disp_name

    @property
    def min(self) -> int:
        """Gets the min of this ParamItemInput.


        :return: The min of this ParamItemInput.
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min: int):
        """Sets the min of this ParamItemInput.


        :param min: The min of this ParamItemInput.
        :type min: int
        """
        if min is None:
            raise ValueError("Invalid value for `min`, must not be `None`")  # noqa: E501

        self._min = min

    @property
    def increment(self) -> int:
        """Gets the increment of this ParamItemInput.


        :return: The increment of this ParamItemInput.
        :rtype: int
        """
        return self._increment

    @increment.setter
    def increment(self, increment: int):
        """Sets the increment of this ParamItemInput.


        :param increment: The increment of this ParamItemInput.
        :type increment: int
        """
        if increment is None:
            raise ValueError("Invalid value for `increment`, must not be `None`")  # noqa: E501

        self._increment = increment
