from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.attribute import Attribute
from openapi_server import util

from openapi_server.models.attribute import Attribute  # noqa: E501

class Product(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, prod_id=None, prefix=None, prd_type=None, cfg_type=None, attributes=None, sort_order=None):  # noqa: E501
        """Product - a model defined in OpenAPI

        :param prod_id: The prod_id of this Product.  # noqa: E501
        :type prod_id: int
        :param prefix: The prefix of this Product.  # noqa: E501
        :type prefix: str
        :param prd_type: The prd_type of this Product.  # noqa: E501
        :type prd_type: str
        :param cfg_type: The cfg_type of this Product.  # noqa: E501
        :type cfg_type: str
        :param attributes: The attributes of this Product.  # noqa: E501
        :type attributes: List[Attribute]
        :param sort_order: The sort_order of this Product.  # noqa: E501
        :type sort_order: int
        """
        self.openapi_types = {
            'prod_id': int,
            'prefix': str,
            'prd_type': str,
            'cfg_type': str,
            'attributes': List[Attribute],
            'sort_order': int
        }

        self.attribute_map = {
            'prod_id': 'prod_id',
            'prefix': 'prefix',
            'prd_type': 'prd_type',
            'cfg_type': 'cfg_type',
            'attributes': 'attributes',
            'sort_order': 'sort_order'
        }

        self._prod_id = prod_id
        self._prefix = prefix
        self._prd_type = prd_type
        self._cfg_type = cfg_type
        self._attributes = attributes
        self._sort_order = sort_order

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.  # noqa: E501
        :rtype: Product
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prod_id(self) -> int:
        """Gets the prod_id of this Product.


        :return: The prod_id of this Product.
        :rtype: int
        """
        return self._prod_id

    @prod_id.setter
    def prod_id(self, prod_id: int):
        """Sets the prod_id of this Product.


        :param prod_id: The prod_id of this Product.
        :type prod_id: int
        """
        if prod_id is None:
            raise ValueError("Invalid value for `prod_id`, must not be `None`")  # noqa: E501

        self._prod_id = prod_id

    @property
    def prefix(self) -> str:
        """Gets the prefix of this Product.


        :return: The prefix of this Product.
        :rtype: str
        """
        return self._prefix

    @prefix.setter
    def prefix(self, prefix: str):
        """Sets the prefix of this Product.


        :param prefix: The prefix of this Product.
        :type prefix: str
        """
        if prefix is None:
            raise ValueError("Invalid value for `prefix`, must not be `None`")  # noqa: E501

        self._prefix = prefix

    @property
    def prd_type(self) -> str:
        """Gets the prd_type of this Product.


        :return: The prd_type of this Product.
        :rtype: str
        """
        return self._prd_type

    @prd_type.setter
    def prd_type(self, prd_type: str):
        """Sets the prd_type of this Product.


        :param prd_type: The prd_type of this Product.
        :type prd_type: str
        """
        if prd_type is None:
            raise ValueError("Invalid value for `prd_type`, must not be `None`")  # noqa: E501

        self._prd_type = prd_type

    @property
    def cfg_type(self) -> str:
        """Gets the cfg_type of this Product.


        :return: The cfg_type of this Product.
        :rtype: str
        """
        return self._cfg_type

    @cfg_type.setter
    def cfg_type(self, cfg_type: str):
        """Sets the cfg_type of this Product.


        :param cfg_type: The cfg_type of this Product.
        :type cfg_type: str
        """
        if cfg_type is None:
            raise ValueError("Invalid value for `cfg_type`, must not be `None`")  # noqa: E501

        self._cfg_type = cfg_type

    @property
    def attributes(self) -> List[Attribute]:
        """Gets the attributes of this Product.


        :return: The attributes of this Product.
        :rtype: List[Attribute]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[Attribute]):
        """Sets the attributes of this Product.


        :param attributes: The attributes of this Product.
        :type attributes: List[Attribute]
        """
        if attributes is None:
            raise ValueError("Invalid value for `attributes`, must not be `None`")  # noqa: E501

        self._attributes = attributes

    @property
    def sort_order(self) -> int:
        """Gets the sort_order of this Product.


        :return: The sort_order of this Product.
        :rtype: int
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order: int):
        """Sets the sort_order of this Product.


        :param sort_order: The sort_order of this Product.
        :type sort_order: int
        """
        if sort_order is None:
            raise ValueError("Invalid value for `sort_order`, must not be `None`")  # noqa: E501

        self._sort_order = sort_order
