/* tslint:disable */
/* eslint-disable */
/**
 * Sample Product API
 * API for managing products and attributes. Params are managed via dedicated endpoints. Attribute creation/update does not include params list directly. \'param\' field in Attribute renamed to \'params\'. Corrected tags for DELETE methods.
 *
 * The version of the OpenAPI document: v1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RefreshMockData200Response,
} from '../models/index';
import {
    RefreshMockData200ResponseFromJSON,
    RefreshMockData200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class UtilitiesApi extends runtime.BaseAPI {

    /**
     * Reset all mock data to its initial state
     */
    async refreshMockDataRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RefreshMockData200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/refresh`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RefreshMockData200ResponseFromJSON(jsonValue));
    }

    /**
     * Reset all mock data to its initial state
     */
    async refreshMockData(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RefreshMockData200Response> {
        const response = await this.refreshMockDataRaw(initOverrides);
        return await response.value();
    }

}
