from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AttributeType3Input(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, disp_name=None, unit=None, type=None, data_type=None, setting_type=None, mgmt_flg=None, sec_mask=None, input_format=None, width=None, max=None, min=None, required_flg=None, list_flg=None, ui_flg=None, api_cls=None, edit_cls=None, cont_cls=None, sort_order=None, init_online=None, init_paper=None, check=None):  # noqa: E501
        """AttributeType3Input - a model defined in OpenAPI

        :param disp_name: The disp_name of this AttributeType3Input.  # noqa: E501
        :type disp_name: str
        :param unit: The unit of this AttributeType3Input.  # noqa: E501
        :type unit: str
        :param type: The type of this AttributeType3Input.  # noqa: E501
        :type type: str
        :param data_type: The data_type of this AttributeType3Input.  # noqa: E501
        :type data_type: str
        :param setting_type: The setting_type of this AttributeType3Input.  # noqa: E501
        :type setting_type: str
        :param mgmt_flg: The mgmt_flg of this AttributeType3Input.  # noqa: E501
        :type mgmt_flg: bool
        :param sec_mask: The sec_mask of this AttributeType3Input.  # noqa: E501
        :type sec_mask: bool
        :param input_format: The input_format of this AttributeType3Input.  # noqa: E501
        :type input_format: str
        :param width: The width of this AttributeType3Input.  # noqa: E501
        :type width: int
        :param max: The max of this AttributeType3Input.  # noqa: E501
        :type max: int
        :param min: The min of this AttributeType3Input.  # noqa: E501
        :type min: int
        :param required_flg: The required_flg of this AttributeType3Input.  # noqa: E501
        :type required_flg: bool
        :param list_flg: The list_flg of this AttributeType3Input.  # noqa: E501
        :type list_flg: bool
        :param ui_flg: The ui_flg of this AttributeType3Input.  # noqa: E501
        :type ui_flg: bool
        :param api_cls: The api_cls of this AttributeType3Input.  # noqa: E501
        :type api_cls: str
        :param edit_cls: The edit_cls of this AttributeType3Input.  # noqa: E501
        :type edit_cls: str
        :param cont_cls: The cont_cls of this AttributeType3Input.  # noqa: E501
        :type cont_cls: str
        :param sort_order: The sort_order of this AttributeType3Input.  # noqa: E501
        :type sort_order: int
        :param init_online: The init_online of this AttributeType3Input.  # noqa: E501
        :type init_online: str
        :param init_paper: The init_paper of this AttributeType3Input.  # noqa: E501
        :type init_paper: str
        :param check: The check of this AttributeType3Input.  # noqa: E501
        :type check: str
        """
        self.openapi_types = {
            'disp_name': str,
            'unit': str,
            'type': str,
            'data_type': str,
            'setting_type': str,
            'mgmt_flg': bool,
            'sec_mask': bool,
            'input_format': str,
            'width': int,
            'max': int,
            'min': int,
            'required_flg': bool,
            'list_flg': bool,
            'ui_flg': bool,
            'api_cls': str,
            'edit_cls': str,
            'cont_cls': str,
            'sort_order': int,
            'init_online': str,
            'init_paper': str,
            'check': str
        }

        self.attribute_map = {
            'disp_name': 'disp_name',
            'unit': 'unit',
            'type': 'type',
            'data_type': 'data_type',
            'setting_type': 'setting_type',
            'mgmt_flg': 'mgmt_flg',
            'sec_mask': 'sec_mask',
            'input_format': 'input_format',
            'width': 'width',
            'max': 'max',
            'min': 'min',
            'required_flg': 'required_flg',
            'list_flg': 'list_flg',
            'ui_flg': 'ui_flg',
            'api_cls': 'api_cls',
            'edit_cls': 'edit_cls',
            'cont_cls': 'cont_cls',
            'sort_order': 'sort_order',
            'init_online': 'init_online',
            'init_paper': 'init_paper',
            'check': 'check'
        }

        self._disp_name = disp_name
        self._unit = unit
        self._type = type
        self._data_type = data_type
        self._setting_type = setting_type
        self._mgmt_flg = mgmt_flg
        self._sec_mask = sec_mask
        self._input_format = input_format
        self._width = width
        self._max = max
        self._min = min
        self._required_flg = required_flg
        self._list_flg = list_flg
        self._ui_flg = ui_flg
        self._api_cls = api_cls
        self._edit_cls = edit_cls
        self._cont_cls = cont_cls
        self._sort_order = sort_order
        self._init_online = init_online
        self._init_paper = init_paper
        self._check = check

    @classmethod
    def from_dict(cls, dikt) -> 'AttributeType3Input':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AttributeType3Input of this AttributeType3Input.  # noqa: E501
        :rtype: AttributeType3Input
        """
        return util.deserialize_model(dikt, cls)

    @property
    def disp_name(self) -> str:
        """Gets the disp_name of this AttributeType3Input.


        :return: The disp_name of this AttributeType3Input.
        :rtype: str
        """
        return self._disp_name

    @disp_name.setter
    def disp_name(self, disp_name: str):
        """Sets the disp_name of this AttributeType3Input.


        :param disp_name: The disp_name of this AttributeType3Input.
        :type disp_name: str
        """
        if disp_name is None:
            raise ValueError("Invalid value for `disp_name`, must not be `None`")  # noqa: E501

        self._disp_name = disp_name

    @property
    def unit(self) -> str:
        """Gets the unit of this AttributeType3Input.


        :return: The unit of this AttributeType3Input.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this AttributeType3Input.


        :param unit: The unit of this AttributeType3Input.
        :type unit: str
        """
        if unit is None:
            raise ValueError("Invalid value for `unit`, must not be `None`")  # noqa: E501

        self._unit = unit

    @property
    def type(self) -> str:
        """Gets the type of this AttributeType3Input.


        :return: The type of this AttributeType3Input.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this AttributeType3Input.


        :param type: The type of this AttributeType3Input.
        :type type: str
        """
        allowed_values = ["type3"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def data_type(self) -> str:
        """Gets the data_type of this AttributeType3Input.


        :return: The data_type of this AttributeType3Input.
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type: str):
        """Sets the data_type of this AttributeType3Input.


        :param data_type: The data_type of this AttributeType3Input.
        :type data_type: str
        """
        if data_type is None:
            raise ValueError("Invalid value for `data_type`, must not be `None`")  # noqa: E501

        self._data_type = data_type

    @property
    def setting_type(self) -> str:
        """Gets the setting_type of this AttributeType3Input.


        :return: The setting_type of this AttributeType3Input.
        :rtype: str
        """
        return self._setting_type

    @setting_type.setter
    def setting_type(self, setting_type: str):
        """Sets the setting_type of this AttributeType3Input.


        :param setting_type: The setting_type of this AttributeType3Input.
        :type setting_type: str
        """
        if setting_type is None:
            raise ValueError("Invalid value for `setting_type`, must not be `None`")  # noqa: E501

        self._setting_type = setting_type

    @property
    def mgmt_flg(self) -> bool:
        """Gets the mgmt_flg of this AttributeType3Input.


        :return: The mgmt_flg of this AttributeType3Input.
        :rtype: bool
        """
        return self._mgmt_flg

    @mgmt_flg.setter
    def mgmt_flg(self, mgmt_flg: bool):
        """Sets the mgmt_flg of this AttributeType3Input.


        :param mgmt_flg: The mgmt_flg of this AttributeType3Input.
        :type mgmt_flg: bool
        """
        if mgmt_flg is None:
            raise ValueError("Invalid value for `mgmt_flg`, must not be `None`")  # noqa: E501

        self._mgmt_flg = mgmt_flg

    @property
    def sec_mask(self) -> bool:
        """Gets the sec_mask of this AttributeType3Input.


        :return: The sec_mask of this AttributeType3Input.
        :rtype: bool
        """
        return self._sec_mask

    @sec_mask.setter
    def sec_mask(self, sec_mask: bool):
        """Sets the sec_mask of this AttributeType3Input.


        :param sec_mask: The sec_mask of this AttributeType3Input.
        :type sec_mask: bool
        """
        if sec_mask is None:
            raise ValueError("Invalid value for `sec_mask`, must not be `None`")  # noqa: E501

        self._sec_mask = sec_mask

    @property
    def input_format(self) -> str:
        """Gets the input_format of this AttributeType3Input.


        :return: The input_format of this AttributeType3Input.
        :rtype: str
        """
        return self._input_format

    @input_format.setter
    def input_format(self, input_format: str):
        """Sets the input_format of this AttributeType3Input.


        :param input_format: The input_format of this AttributeType3Input.
        :type input_format: str
        """

        self._input_format = input_format

    @property
    def width(self) -> int:
        """Gets the width of this AttributeType3Input.


        :return: The width of this AttributeType3Input.
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width: int):
        """Sets the width of this AttributeType3Input.


        :param width: The width of this AttributeType3Input.
        :type width: int
        """

        self._width = width

    @property
    def max(self) -> int:
        """Gets the max of this AttributeType3Input.


        :return: The max of this AttributeType3Input.
        :rtype: int
        """
        return self._max

    @max.setter
    def max(self, max: int):
        """Sets the max of this AttributeType3Input.


        :param max: The max of this AttributeType3Input.
        :type max: int
        """

        self._max = max

    @property
    def min(self) -> int:
        """Gets the min of this AttributeType3Input.


        :return: The min of this AttributeType3Input.
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min: int):
        """Sets the min of this AttributeType3Input.


        :param min: The min of this AttributeType3Input.
        :type min: int
        """

        self._min = min

    @property
    def required_flg(self) -> bool:
        """Gets the required_flg of this AttributeType3Input.


        :return: The required_flg of this AttributeType3Input.
        :rtype: bool
        """
        return self._required_flg

    @required_flg.setter
    def required_flg(self, required_flg: bool):
        """Sets the required_flg of this AttributeType3Input.


        :param required_flg: The required_flg of this AttributeType3Input.
        :type required_flg: bool
        """
        if required_flg is None:
            raise ValueError("Invalid value for `required_flg`, must not be `None`")  # noqa: E501

        self._required_flg = required_flg

    @property
    def list_flg(self) -> bool:
        """Gets the list_flg of this AttributeType3Input.


        :return: The list_flg of this AttributeType3Input.
        :rtype: bool
        """
        return self._list_flg

    @list_flg.setter
    def list_flg(self, list_flg: bool):
        """Sets the list_flg of this AttributeType3Input.


        :param list_flg: The list_flg of this AttributeType3Input.
        :type list_flg: bool
        """
        if list_flg is None:
            raise ValueError("Invalid value for `list_flg`, must not be `None`")  # noqa: E501

        self._list_flg = list_flg

    @property
    def ui_flg(self) -> bool:
        """Gets the ui_flg of this AttributeType3Input.


        :return: The ui_flg of this AttributeType3Input.
        :rtype: bool
        """
        return self._ui_flg

    @ui_flg.setter
    def ui_flg(self, ui_flg: bool):
        """Sets the ui_flg of this AttributeType3Input.


        :param ui_flg: The ui_flg of this AttributeType3Input.
        :type ui_flg: bool
        """
        if ui_flg is None:
            raise ValueError("Invalid value for `ui_flg`, must not be `None`")  # noqa: E501

        self._ui_flg = ui_flg

    @property
    def api_cls(self) -> str:
        """Gets the api_cls of this AttributeType3Input.


        :return: The api_cls of this AttributeType3Input.
        :rtype: str
        """
        return self._api_cls

    @api_cls.setter
    def api_cls(self, api_cls: str):
        """Sets the api_cls of this AttributeType3Input.


        :param api_cls: The api_cls of this AttributeType3Input.
        :type api_cls: str
        """

        self._api_cls = api_cls

    @property
    def edit_cls(self) -> str:
        """Gets the edit_cls of this AttributeType3Input.


        :return: The edit_cls of this AttributeType3Input.
        :rtype: str
        """
        return self._edit_cls

    @edit_cls.setter
    def edit_cls(self, edit_cls: str):
        """Sets the edit_cls of this AttributeType3Input.


        :param edit_cls: The edit_cls of this AttributeType3Input.
        :type edit_cls: str
        """

        self._edit_cls = edit_cls

    @property
    def cont_cls(self) -> str:
        """Gets the cont_cls of this AttributeType3Input.


        :return: The cont_cls of this AttributeType3Input.
        :rtype: str
        """
        return self._cont_cls

    @cont_cls.setter
    def cont_cls(self, cont_cls: str):
        """Sets the cont_cls of this AttributeType3Input.


        :param cont_cls: The cont_cls of this AttributeType3Input.
        :type cont_cls: str
        """

        self._cont_cls = cont_cls

    @property
    def sort_order(self) -> int:
        """Gets the sort_order of this AttributeType3Input.


        :return: The sort_order of this AttributeType3Input.
        :rtype: int
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order: int):
        """Sets the sort_order of this AttributeType3Input.


        :param sort_order: The sort_order of this AttributeType3Input.
        :type sort_order: int
        """

        self._sort_order = sort_order

    @property
    def init_online(self) -> str:
        """Gets the init_online of this AttributeType3Input.


        :return: The init_online of this AttributeType3Input.
        :rtype: str
        """
        return self._init_online

    @init_online.setter
    def init_online(self, init_online: str):
        """Sets the init_online of this AttributeType3Input.


        :param init_online: The init_online of this AttributeType3Input.
        :type init_online: str
        """

        self._init_online = init_online

    @property
    def init_paper(self) -> str:
        """Gets the init_paper of this AttributeType3Input.


        :return: The init_paper of this AttributeType3Input.
        :rtype: str
        """
        return self._init_paper

    @init_paper.setter
    def init_paper(self, init_paper: str):
        """Sets the init_paper of this AttributeType3Input.


        :param init_paper: The init_paper of this AttributeType3Input.
        :type init_paper: str
        """

        self._init_paper = init_paper

    @property
    def check(self) -> str:
        """Gets the check of this AttributeType3Input.


        :return: The check of this AttributeType3Input.
        :rtype: str
        """
        return self._check

    @check.setter
    def check(self, check: str):
        """Sets the check of this AttributeType3Input.


        :param check: The check of this AttributeType3Input.
        :type check: str
        """

        self._check = check
