from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AttributeType2CreationInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, attribute_code=None, disp_name=None, unit=None, type=None, type2_number=None, max=None, min=None, increment=None):  # noqa: E501
        """AttributeType2CreationInput - a model defined in OpenAPI

        :param attribute_code: The attribute_code of this AttributeType2CreationInput.  # noqa: E501
        :type attribute_code: str
        :param disp_name: The disp_name of this AttributeType2CreationInput.  # noqa: E501
        :type disp_name: str
        :param unit: The unit of this AttributeType2CreationInput.  # noqa: E501
        :type unit: str
        :param type: The type of this AttributeType2CreationInput.  # noqa: E501
        :type type: str
        :param type2_number: The type2_number of this AttributeType2CreationInput.  # noqa: E501
        :type type2_number: int
        :param max: The max of this AttributeType2CreationInput.  # noqa: E501
        :type max: int
        :param min: The min of this AttributeType2CreationInput.  # noqa: E501
        :type min: int
        :param increment: The increment of this AttributeType2CreationInput.  # noqa: E501
        :type increment: int
        """
        self.openapi_types = {
            'attribute_code': str,
            'disp_name': str,
            'unit': str,
            'type': str,
            'type2_number': int,
            'max': int,
            'min': int,
            'increment': int
        }

        self.attribute_map = {
            'attribute_code': 'attribute_code',
            'disp_name': 'disp_name',
            'unit': 'unit',
            'type': 'type',
            'type2_number': 'type2_number',
            'max': 'max',
            'min': 'min',
            'increment': 'increment'
        }

        self._attribute_code = attribute_code
        self._disp_name = disp_name
        self._unit = unit
        self._type = type
        self._type2_number = type2_number
        self._max = max
        self._min = min
        self._increment = increment

    @classmethod
    def from_dict(cls, dikt) -> 'AttributeType2CreationInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AttributeType2CreationInput of this AttributeType2CreationInput.  # noqa: E501
        :rtype: AttributeType2CreationInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attribute_code(self) -> str:
        """Gets the attribute_code of this AttributeType2CreationInput.


        :return: The attribute_code of this AttributeType2CreationInput.
        :rtype: str
        """
        return self._attribute_code

    @attribute_code.setter
    def attribute_code(self, attribute_code: str):
        """Sets the attribute_code of this AttributeType2CreationInput.


        :param attribute_code: The attribute_code of this AttributeType2CreationInput.
        :type attribute_code: str
        """
        if attribute_code is None:
            raise ValueError("Invalid value for `attribute_code`, must not be `None`")  # noqa: E501

        self._attribute_code = attribute_code

    @property
    def disp_name(self) -> str:
        """Gets the disp_name of this AttributeType2CreationInput.


        :return: The disp_name of this AttributeType2CreationInput.
        :rtype: str
        """
        return self._disp_name

    @disp_name.setter
    def disp_name(self, disp_name: str):
        """Sets the disp_name of this AttributeType2CreationInput.


        :param disp_name: The disp_name of this AttributeType2CreationInput.
        :type disp_name: str
        """
        if disp_name is None:
            raise ValueError("Invalid value for `disp_name`, must not be `None`")  # noqa: E501

        self._disp_name = disp_name

    @property
    def unit(self) -> str:
        """Gets the unit of this AttributeType2CreationInput.


        :return: The unit of this AttributeType2CreationInput.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this AttributeType2CreationInput.


        :param unit: The unit of this AttributeType2CreationInput.
        :type unit: str
        """
        if unit is None:
            raise ValueError("Invalid value for `unit`, must not be `None`")  # noqa: E501

        self._unit = unit

    @property
    def type(self) -> str:
        """Gets the type of this AttributeType2CreationInput.


        :return: The type of this AttributeType2CreationInput.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this AttributeType2CreationInput.


        :param type: The type of this AttributeType2CreationInput.
        :type type: str
        """
        allowed_values = ["type2"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def type2_number(self) -> int:
        """Gets the type2_number of this AttributeType2CreationInput.


        :return: The type2_number of this AttributeType2CreationInput.
        :rtype: int
        """
        return self._type2_number

    @type2_number.setter
    def type2_number(self, type2_number: int):
        """Sets the type2_number of this AttributeType2CreationInput.


        :param type2_number: The type2_number of this AttributeType2CreationInput.
        :type type2_number: int
        """
        if type2_number is None:
            raise ValueError("Invalid value for `type2_number`, must not be `None`")  # noqa: E501

        self._type2_number = type2_number

    @property
    def max(self) -> int:
        """Gets the max of this AttributeType2CreationInput.


        :return: The max of this AttributeType2CreationInput.
        :rtype: int
        """
        return self._max

    @max.setter
    def max(self, max: int):
        """Sets the max of this AttributeType2CreationInput.


        :param max: The max of this AttributeType2CreationInput.
        :type max: int
        """
        if max is None:
            raise ValueError("Invalid value for `max`, must not be `None`")  # noqa: E501

        self._max = max

    @property
    def min(self) -> int:
        """Gets the min of this AttributeType2CreationInput.


        :return: The min of this AttributeType2CreationInput.
        :rtype: int
        """
        return self._min

    @min.setter
    def min(self, min: int):
        """Sets the min of this AttributeType2CreationInput.


        :param min: The min of this AttributeType2CreationInput.
        :type min: int
        """
        if min is None:
            raise ValueError("Invalid value for `min`, must not be `None`")  # noqa: E501

        self._min = min

    @property
    def increment(self) -> int:
        """Gets the increment of this AttributeType2CreationInput.


        :return: The increment of this AttributeType2CreationInput.
        :rtype: int
        """
        return self._increment

    @increment.setter
    def increment(self, increment: int):
        """Sets the increment of this AttributeType2CreationInput.


        :param increment: The increment of this AttributeType2CreationInput.
        :type increment: int
        """
        if increment is None:
            raise ValueError("Invalid value for `increment`, must not be `None`")  # noqa: E501

        self._increment = increment
