from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AttributeType1CreationInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, attribute_code=None, disp_name=None, unit=None, type=None, type1_number=None, required_flg=None):  # noqa: E501
        """AttributeType1CreationInput - a model defined in OpenAPI

        :param attribute_code: The attribute_code of this AttributeType1CreationInput.  # noqa: E501
        :type attribute_code: str
        :param disp_name: The disp_name of this AttributeType1CreationInput.  # noqa: E501
        :type disp_name: str
        :param unit: The unit of this AttributeType1CreationInput.  # noqa: E501
        :type unit: str
        :param type: The type of this AttributeType1CreationInput.  # noqa: E501
        :type type: str
        :param type1_number: The type1_number of this AttributeType1CreationInput.  # noqa: E501
        :type type1_number: int
        :param required_flg: The required_flg of this AttributeType1CreationInput.  # noqa: E501
        :type required_flg: bool
        """
        self.openapi_types = {
            'attribute_code': str,
            'disp_name': str,
            'unit': str,
            'type': str,
            'type1_number': int,
            'required_flg': bool
        }

        self.attribute_map = {
            'attribute_code': 'attribute_code',
            'disp_name': 'disp_name',
            'unit': 'unit',
            'type': 'type',
            'type1_number': 'type1_number',
            'required_flg': 'required_flg'
        }

        self._attribute_code = attribute_code
        self._disp_name = disp_name
        self._unit = unit
        self._type = type
        self._type1_number = type1_number
        self._required_flg = required_flg

    @classmethod
    def from_dict(cls, dikt) -> 'AttributeType1CreationInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AttributeType1CreationInput of this AttributeType1CreationInput.  # noqa: E501
        :rtype: AttributeType1CreationInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attribute_code(self) -> str:
        """Gets the attribute_code of this AttributeType1CreationInput.


        :return: The attribute_code of this AttributeType1CreationInput.
        :rtype: str
        """
        return self._attribute_code

    @attribute_code.setter
    def attribute_code(self, attribute_code: str):
        """Sets the attribute_code of this AttributeType1CreationInput.


        :param attribute_code: The attribute_code of this AttributeType1CreationInput.
        :type attribute_code: str
        """
        if attribute_code is None:
            raise ValueError("Invalid value for `attribute_code`, must not be `None`")  # noqa: E501

        self._attribute_code = attribute_code

    @property
    def disp_name(self) -> str:
        """Gets the disp_name of this AttributeType1CreationInput.


        :return: The disp_name of this AttributeType1CreationInput.
        :rtype: str
        """
        return self._disp_name

    @disp_name.setter
    def disp_name(self, disp_name: str):
        """Sets the disp_name of this AttributeType1CreationInput.


        :param disp_name: The disp_name of this AttributeType1CreationInput.
        :type disp_name: str
        """
        if disp_name is None:
            raise ValueError("Invalid value for `disp_name`, must not be `None`")  # noqa: E501

        self._disp_name = disp_name

    @property
    def unit(self) -> str:
        """Gets the unit of this AttributeType1CreationInput.


        :return: The unit of this AttributeType1CreationInput.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this AttributeType1CreationInput.


        :param unit: The unit of this AttributeType1CreationInput.
        :type unit: str
        """
        if unit is None:
            raise ValueError("Invalid value for `unit`, must not be `None`")  # noqa: E501

        self._unit = unit

    @property
    def type(self) -> str:
        """Gets the type of this AttributeType1CreationInput.


        :return: The type of this AttributeType1CreationInput.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this AttributeType1CreationInput.


        :param type: The type of this AttributeType1CreationInput.
        :type type: str
        """
        allowed_values = ["type1"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def type1_number(self) -> int:
        """Gets the type1_number of this AttributeType1CreationInput.


        :return: The type1_number of this AttributeType1CreationInput.
        :rtype: int
        """
        return self._type1_number

    @type1_number.setter
    def type1_number(self, type1_number: int):
        """Sets the type1_number of this AttributeType1CreationInput.


        :param type1_number: The type1_number of this AttributeType1CreationInput.
        :type type1_number: int
        """
        if type1_number is None:
            raise ValueError("Invalid value for `type1_number`, must not be `None`")  # noqa: E501

        self._type1_number = type1_number

    @property
    def required_flg(self) -> bool:
        """Gets the required_flg of this AttributeType1CreationInput.


        :return: The required_flg of this AttributeType1CreationInput.
        :rtype: bool
        """
        return self._required_flg

    @required_flg.setter
    def required_flg(self, required_flg: bool):
        """Sets the required_flg of this AttributeType1CreationInput.


        :param required_flg: The required_flg of this AttributeType1CreationInput.
        :type required_flg: bool
        """
        if required_flg is None:
            raise ValueError("Invalid value for `required_flg`, must not be `None`")  # noqa: E501

        self._required_flg = required_flg
