from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AttributeBase(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, attribute_code=None, disp_name=None, unit=None, type=None):  # noqa: E501
        """AttributeBase - a model defined in OpenAPI

        :param attribute_code: The attribute_code of this AttributeBase.  # noqa: E501
        :type attribute_code: str
        :param disp_name: The disp_name of this AttributeBase.  # noqa: E501
        :type disp_name: str
        :param unit: The unit of this AttributeBase.  # noqa: E501
        :type unit: str
        :param type: The type of this AttributeBase.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'attribute_code': str,
            'disp_name': str,
            'unit': str,
            'type': str
        }

        self.attribute_map = {
            'attribute_code': 'attribute_code',
            'disp_name': 'disp_name',
            'unit': 'unit',
            'type': 'type'
        }

        self._attribute_code = attribute_code
        self._disp_name = disp_name
        self._unit = unit
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'AttributeBase':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AttributeBase of this AttributeBase.  # noqa: E501
        :rtype: AttributeBase
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attribute_code(self) -> str:
        """Gets the attribute_code of this AttributeBase.


        :return: The attribute_code of this AttributeBase.
        :rtype: str
        """
        return self._attribute_code

    @attribute_code.setter
    def attribute_code(self, attribute_code: str):
        """Sets the attribute_code of this AttributeBase.


        :param attribute_code: The attribute_code of this AttributeBase.
        :type attribute_code: str
        """
        if attribute_code is None:
            raise ValueError("Invalid value for `attribute_code`, must not be `None`")  # noqa: E501

        self._attribute_code = attribute_code

    @property
    def disp_name(self) -> str:
        """Gets the disp_name of this AttributeBase.


        :return: The disp_name of this AttributeBase.
        :rtype: str
        """
        return self._disp_name

    @disp_name.setter
    def disp_name(self, disp_name: str):
        """Sets the disp_name of this AttributeBase.


        :param disp_name: The disp_name of this AttributeBase.
        :type disp_name: str
        """
        if disp_name is None:
            raise ValueError("Invalid value for `disp_name`, must not be `None`")  # noqa: E501

        self._disp_name = disp_name

    @property
    def unit(self) -> str:
        """Gets the unit of this AttributeBase.


        :return: The unit of this AttributeBase.
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit: str):
        """Sets the unit of this AttributeBase.


        :param unit: The unit of this AttributeBase.
        :type unit: str
        """
        if unit is None:
            raise ValueError("Invalid value for `unit`, must not be `None`")  # noqa: E501

        self._unit = unit

    @property
    def type(self) -> str:
        """Gets the type of this AttributeBase.


        :return: The type of this AttributeBase.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this AttributeBase.


        :param type: The type of this AttributeBase.
        :type type: str
        """
        allowed_values = ["type1", "type2", "type3"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type
