from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.attribute import Attribute
from openapi_server import util

from openapi_server.models.attribute import Attribute  # noqa: E501

class Component(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, components_type=None, component_name=None, deliv_flg=None, label_cls=None, attributes=None):  # noqa: E501
        """Component - a model defined in OpenAPI

        :param components_type: The components_type of this Component.  # noqa: E501
        :type components_type: str
        :param component_name: The component_name of this Component.  # noqa: E501
        :type component_name: str
        :param deliv_flg: The deliv_flg of this Component.  # noqa: E501
        :type deliv_flg: bool
        :param label_cls: The label_cls of this Component.  # noqa: E501
        :type label_cls: str
        :param attributes: The attributes of this Component.  # noqa: E501
        :type attributes: List[Attribute]
        """
        self.openapi_types = {
            'components_type': str,
            'component_name': str,
            'deliv_flg': bool,
            'label_cls': str,
            'attributes': List[Attribute]
        }

        self.attribute_map = {
            'components_type': 'components_type',
            'component_name': 'component_name',
            'deliv_flg': 'deliv_flg',
            'label_cls': 'label_cls',
            'attributes': 'attributes'
        }

        self._components_type = components_type
        self._component_name = component_name
        self._deliv_flg = deliv_flg
        self._label_cls = label_cls
        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'Component':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Component of this Component.  # noqa: E501
        :rtype: Component
        """
        return util.deserialize_model(dikt, cls)

    @property
    def components_type(self) -> str:
        """Gets the components_type of this Component.


        :return: The components_type of this Component.
        :rtype: str
        """
        return self._components_type

    @components_type.setter
    def components_type(self, components_type: str):
        """Sets the components_type of this Component.


        :param components_type: The components_type of this Component.
        :type components_type: str
        """
        if components_type is None:
            raise ValueError("Invalid value for `components_type`, must not be `None`")  # noqa: E501

        self._components_type = components_type

    @property
    def component_name(self) -> str:
        """Gets the component_name of this Component.


        :return: The component_name of this Component.
        :rtype: str
        """
        return self._component_name

    @component_name.setter
    def component_name(self, component_name: str):
        """Sets the component_name of this Component.


        :param component_name: The component_name of this Component.
        :type component_name: str
        """
        if component_name is None:
            raise ValueError("Invalid value for `component_name`, must not be `None`")  # noqa: E501

        self._component_name = component_name

    @property
    def deliv_flg(self) -> bool:
        """Gets the deliv_flg of this Component.


        :return: The deliv_flg of this Component.
        :rtype: bool
        """
        return self._deliv_flg

    @deliv_flg.setter
    def deliv_flg(self, deliv_flg: bool):
        """Sets the deliv_flg of this Component.


        :param deliv_flg: The deliv_flg of this Component.
        :type deliv_flg: bool
        """
        if deliv_flg is None:
            raise ValueError("Invalid value for `deliv_flg`, must not be `None`")  # noqa: E501

        self._deliv_flg = deliv_flg

    @property
    def label_cls(self) -> str:
        """Gets the label_cls of this Component.


        :return: The label_cls of this Component.
        :rtype: str
        """
        return self._label_cls

    @label_cls.setter
    def label_cls(self, label_cls: str):
        """Sets the label_cls of this Component.


        :param label_cls: The label_cls of this Component.
        :type label_cls: str
        """
        if label_cls is None:
            raise ValueError("Invalid value for `label_cls`, must not be `None`")  # noqa: E501

        self._label_cls = label_cls

    @property
    def attributes(self) -> List[Attribute]:
        """Gets the attributes of this Component.


        :return: The attributes of this Component.
        :rtype: List[Attribute]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: List[Attribute]):
        """Sets the attributes of this Component.


        :param attributes: The attributes of this Component.
        :type attributes: List[Attribute]
        """
        if attributes is None:
            raise ValueError("Invalid value for `attributes`, must not be `None`")  # noqa: E501

        self._attributes = attributes
