from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Param(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, param_code=None, disp_name=None, sort_order=None, order_stop_data=None):  # noqa: E501
        """Param - a model defined in OpenAPI

        :param param_code: The param_code of this Param.  # noqa: E501
        :type param_code: str
        :param disp_name: The disp_name of this Param.  # noqa: E501
        :type disp_name: str
        :param sort_order: The sort_order of this Param.  # noqa: E501
        :type sort_order: int
        :param order_stop_data: The order_stop_data of this Param.  # noqa: E501
        :type order_stop_data: str
        """
        self.openapi_types = {
            'param_code': str,
            'disp_name': str,
            'sort_order': int,
            'order_stop_data': str
        }

        self.attribute_map = {
            'param_code': 'param_code',
            'disp_name': 'disp_name',
            'sort_order': 'sort_order',
            'order_stop_data': 'order_stop_data'
        }

        self._param_code = param_code
        self._disp_name = disp_name
        self._sort_order = sort_order
        self._order_stop_data = order_stop_data

    @classmethod
    def from_dict(cls, dikt) -> 'Param':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Param of this Param.  # noqa: E501
        :rtype: Param
        """
        return util.deserialize_model(dikt, cls)

    @property
    def param_code(self) -> str:
        """Gets the param_code of this Param.


        :return: The param_code of this Param.
        :rtype: str
        """
        return self._param_code

    @param_code.setter
    def param_code(self, param_code: str):
        """Sets the param_code of this Param.


        :param param_code: The param_code of this Param.
        :type param_code: str
        """
        if param_code is None:
            raise ValueError("Invalid value for `param_code`, must not be `None`")  # noqa: E501

        self._param_code = param_code

    @property
    def disp_name(self) -> str:
        """Gets the disp_name of this Param.


        :return: The disp_name of this Param.
        :rtype: str
        """
        return self._disp_name

    @disp_name.setter
    def disp_name(self, disp_name: str):
        """Sets the disp_name of this Param.


        :param disp_name: The disp_name of this Param.
        :type disp_name: str
        """
        if disp_name is None:
            raise ValueError("Invalid value for `disp_name`, must not be `None`")  # noqa: E501

        self._disp_name = disp_name

    @property
    def sort_order(self) -> int:
        """Gets the sort_order of this Param.


        :return: The sort_order of this Param.
        :rtype: int
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order: int):
        """Sets the sort_order of this Param.


        :param sort_order: The sort_order of this Param.
        :type sort_order: int
        """
        if sort_order is None:
            raise ValueError("Invalid value for `sort_order`, must not be `None`")  # noqa: E501

        self._sort_order = sort_order

    @property
    def order_stop_data(self) -> str:
        """Gets the order_stop_data of this Param.


        :return: The order_stop_data of this Param.
        :rtype: str
        """
        return self._order_stop_data

    @order_stop_data.setter
    def order_stop_data(self, order_stop_data: str):
        """Sets the order_stop_data of this Param.


        :param order_stop_data: The order_stop_data of this Param.
        :type order_stop_data: str
        """

        self._order_stop_data = order_stop_data
