from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.component import Component
from openapi_server import util

from openapi_server.models.component import Component  # noqa: E501

class Product(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, prod_id=None, components=None):  # noqa: E501
        """Product - a model defined in OpenAPI

        :param prod_id: The prod_id of this Product.  # noqa: E501
        :type prod_id: str
        :param components: The components of this Product.  # noqa: E501
        :type components: List[Component]
        """
        self.openapi_types = {
            'prod_id': str,
            'components': List[Component]
        }

        self.attribute_map = {
            'prod_id': 'prod_id',
            'components': 'components'
        }

        self._prod_id = prod_id
        self._components = components

    @classmethod
    def from_dict(cls, dikt) -> 'Product':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Product of this Product.  # noqa: E501
        :rtype: Product
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prod_id(self) -> str:
        """Gets the prod_id of this Product.


        :return: The prod_id of this Product.
        :rtype: str
        """
        return self._prod_id

    @prod_id.setter
    def prod_id(self, prod_id: str):
        """Sets the prod_id of this Product.


        :param prod_id: The prod_id of this Product.
        :type prod_id: str
        """
        if prod_id is None:
            raise ValueError("Invalid value for `prod_id`, must not be `None`")  # noqa: E501

        self._prod_id = prod_id

    @property
    def components(self) -> List[Component]:
        """Gets the components of this Product.


        :return: The components of this Product.
        :rtype: List[Component]
        """
        return self._components

    @components.setter
    def components(self, components: List[Component]):
        """Sets the components of this Product.


        :param components: The components of this Product.
        :type components: List[Component]
        """
        if components is None:
            raise ValueError("Invalid value for `components`, must not be `None`")  # noqa: E501

        self._components = components
